### ISSUE TITLE
Peer to peer code project reviews 

### ISSUE THREAD

**Issue by stenlisuryadinata** [christianonoh/Portfolio-Website#4]
In the following project, we observe that the layout was set up with a grid, my suggestion would be to be more careful with how it was set up so t doesn't create any conflict with other functions.

@zam-cham

**Comment by Danfall369** [comment]
Note that your navbar doesn't lead anywhere, could you please fix that, try linking the corresponding places in the navbar elements with a <a> tag and the "href" with the id of the corresponding place.
